services:
  svc:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spot
