services:
  auth-svc:
    build: .
    depends_on:
      - db-svc
    environment:
      - PACKAGE=spot-auth
    ports:
      - '5001:5001'

  db-svc:
    build:
      context: .
    depends_on:
      - pgsql
    environment:
      - DB_URL=postgres://user:password@pgsql:5432/spot
      - PACKAGE=spot-db

  pgsql:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spot
    ports:
      - '5432:5432'
