import typescript from '@rollup/plugin-typescript'
import cleaner from 'rollup-plugin-cleaner'

export default {
	input: 'src/index.ts',
	output: {
		file: 'dist/index.js',
		format: 'cjs',
		exports: 'auto'
	},
	// Clean out index.js generated by tsc, leave declarations
	plugins: [cleaner({ targets: ['dist/index.js'] }), typescript()],
	external: ['@grpc/proto-loader', 'grpc', 'path']
}
