extends:
  - 'spot'
  - 'plugin:react/recommended'
rules:
  react/react-in-jsx-scope: 0
  react/jsx-filename-extension: 0
  react/jsx-props-no-spreading: 0
  react/jsx-indent: 0
  react/jsx-indent-props: 0
  react/jsx-one-expression-per-line: 0
  react/prop-types: 0
  import/extensions: 0
  no-nested-ternary: 0
  import/prefer-default-export: 0
  no-console: 0
