name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.14
      - uses: extractions/setup-just@v1
        with:
          just-version: '*'
      - run: just ci
